language: java
sudo: required
script:
 - gradle check
 - gradle cucumber

before_install:
 - chmod +x gradlew
 - mysql -e "create database IF NOT EXISTS webapp;" -uroot

jdk:
 - oraclejdk7
 - openjdk7

services:
- mysql

notifications:
  email: false
