language: java

sudo: required

script:
 - ./gradlew -i check

before_install:
 - chmod +x gradlew
 - mysql -e "create database IF NOT EXISTS webapp;" -uroot

jdk:
 - oraclejdk7
 - openjdk7

services:
- mysql

after_success:

notifications:
  email: false


